#%RAML 1.0 Library

types:
  lead:
    description: post the leads
    type: object
    properties:
      city:
        description: city
        type: string
        required: false
      discription:
        description: it gives description
        type: string
        required: false
      company:
         description: company
         type: string
         required: true
      country:
        description: country
        type: string
        required: false
      email:
         description: email
         type: string
         required: false
      first_name:
        description: firstname
        type: string
        required: false
      last_name:
        description: lastname
        type: string
        required: true
      phone:
        description: phonenumber
        type: string
        required: false
      postal_code:
        description: postalcode
        type: string
        required: false
      state:
        description: state
        type: string
        required: false
      title:
        description: title
        type: string
        required: false
      sync_new_record_to_db:
        description: syncnewrecordtodb
        type: string
        required: false
      sync_update_record_to_db:
        description: syncupdaterecordtodb
        type: string
        required: false
      external_id: 
       description: external_id
       type: integer
       required: false

  post_lead_request:
   type: array
   items: lead
     


  post_lead_response:
   properties:
      is_success :
        description: Success
        type: boolean
        required: true
      response:
        type: array
        items:
          type: object
          properties:
           payload:
            type: object
            properties:
              success: boolean
              id: string
              errors: array
